### ISSUE TITLE
Is it possible to move test-data away from /conf?

### ISSUE THREAD

**Issue by ahlag** [feathr-ai/feathr-online#21]
@windoze (cc: @blrchen)

We are currently overwrite `/conf` in `feathr-aks`. When `test-data` is overwritten and dissapeared, `feathr-online` crashes.

**Comment by windoze** [comment]
To overwrite `/conf`, you need:
1. Check every entry in the `lookup.json` file, make sure they're not using anything that doesn't exist.
2. Check every pipeline defined in the `pipeline.conf` file, make sure they're not referring to any non-existent lookup source.

Basically it means you need to completely rewrite these 2 files, everything in these demo configuration files is for demo only, you shouldn't keep them for any other usage.

**Comment by ahlag** [comment]
Hi @windoze,

Thank you so much! I managed to removed all the environment variables and reference to such files from `lookup.json` and `pipeline.conf`. Thank you so much for the explanation.
